[package]
name = "raytrace-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["png", "hdr"] }
profiling = "1.0.17"
rand = { version = "0.10.0", default-features = false, features = ["std", "thread_rng"] }
rayon = "1.11.0"
tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

winit = { version = "0.30.13", default-features = false, features = ["wayland", "rwh_06"] }
softbuffer = { version = "0.4.8", default-features = false, features = ["wayland"] }
smol = "2.0.2"
async-tungstenite = { version = "0.34.1", default-features = false, features = ["handshake", "futures-03-sink"] }
futures-lite = { version = "2.6.1", default-features = false, features = ["std"] }

[features]
default = ["profile-with-tracing"]
profile-with-tracing = ["profiling/profile-with-tracing"]
profile-with-puffin = ["profiling/profile-with-puffin"]
profile-with-tracy = ["profiling/profile-with-tracy"]
profile-with-optick = ["profiling/profile-with-optick"]
