use crate::math::vec3::Color3;
use crate::ray::Ray;
use crate::sampler::{SampleStream, SamplerRng};

pub mod perspective;

/// Camera sample data for a single ray generation.
pub struct CameraSampler {
    /// Pixel coordinates for the sample (x, y).
    pub pixel: (u32, u32),
    /// Anti-aliasing jitter within the pixel (0.0 to 1.0).
    pub jitter: (f32, f32),
    /// Lens sample for depth of field (0.0 to 1.0).
    pub lens: (f32, f32),
    /// Time for motion blur (0.0 to 1.0, where 0.0 is the start of the shutter and 1.0 is the end).
    pub time: f32,
}

impl CameraSampler {
    pub fn new(pixel: (u32, u32), jitter: (f32, f32), lens: (f32, f32), time: f32) -> Self {
        Self {
            pixel,
            jitter,
            lens,
            time: time.clamp(0.0, 1.0),
        }
    }
}

/// Generic camera sample construction.
///
/// Draws pixel AA jitter, lens position, and time from a stream+rng pair.
/// Consumes: 2× stream.next_2d (jitter, lens), 1× rng.next (time).
pub fn get_camera_sample<S: SampleStream, R: SamplerRng>(
    pixel: (u32, u32),
    stream: &mut S,
    rng: &mut R,
) -> CameraSampler {
    let (jx, jy) = stream.next_2d();
    let (lx, ly) = stream.next_2d();
    CameraSampler {
        pixel,
        jitter: (jx, jy),
        lens: (lx, ly),
        time: rng.next().clamp(0.0, 1.0),
    }
}

/// A ray generated by the camera, along with its associated weight.
pub struct CameraRay {
    /// The ray generated by the camera for this sample, in world space.
    pub ray: Ray,
    /// The weight of the ray, which may include factors like lens sampling and motion blur.
    pub weight: Color3,
}

/// A trait for camera models that can generate rays for rendering.
pub trait Camera: Send + Sync {
    /// Generates a ray for the given camera sample. The ray is in world space.
    fn generate_ray(&self, sample: &CameraSampler) -> Option<CameraRay>;

    /// Generates ray differentials for the given camera sample, if supported, for texture filtering and anti-aliasing.
    fn generate_ray_differential(&self, sample: &CameraSampler) -> Option<CameraRay> {
        let _ = sample;
        // No differentials by default, but can be overridden by cameras that support them (e.g. perspective camera).
        None
    }

    /// Returns the resolution of the camera's image plane (width, height).
    fn image_resolution(&self) -> (u32, u32);
}
