pub mod perspective;

pub use perspective::PerspectiveCamera;

use crate::ray::Ray;
use crate::vec3::Color3;

pub struct CameraSampler {
    /// Pixel coordinates for the sample (x, y).
    pub pixel: (u32, u32),
    /// Anti-aliasing jitter within the pixel (0.0 to 1.0).
    pub jitter: (f64, f64),
    /// Lens sample for depth of field (0.0 to 1.0).
    pub lens: (f64, f64),
    /// Time for motion blur (0.0 to 1.0, where 0.0 is the start of the shutter and 1.0 is the end).
    pub time: f64,
}

pub struct CameraRay {
    /// The ray generated by the camera for this sample, in world space.
    pub ray: Ray,
    /// The weight of the ray, which may include factors like lens sampling and motion blur.
    pub weight: Color3,
}

pub trait Camera: Send + Sync {
    /// Generates a ray for the given camera sample. The ray is in world space.
    fn generate_ray(&self, sample: &CameraSampler) -> Option<CameraRay>;

    /// Generates ray differentials for the given camera sample, if supported, for texture filtering and anti-aliasing.
    fn generate_ray_differential(&self, sample: &CameraSampler) -> Option<CameraRay> {
        let _ = sample;
        // No differentials by default, but can be overridden by cameras that support them (e.g. perspective camera).
        None
    }

    /// Returns the resolution of the camera's image plane (width, height).
    fn image_resolution(&self) -> (u32, u32);
}
