pub mod perspective;

pub use perspective::PerspectiveCamera;

use crate::ray::Ray;
use crate::sampler::{SampleStream, SamplerRng};
use crate::vec3::Color3;

pub struct CameraSampler {
    /// Pixel coordinates for the sample (x, y).
    pub pixel: (u32, u32),
    /// Anti-aliasing jitter within the pixel (0.0 to 1.0).
    pub jitter: (f64, f64),
    /// Lens sample for depth of field (0.0 to 1.0).
    pub lens: (f64, f64),
    /// Time for motion blur (0.0 to 1.0, where 0.0 is the start of the shutter and 1.0 is the end).
    pub time: f64,
}

impl CameraSampler {
    pub fn new(pixel: (u32, u32), jitter: (f64, f64), lens: (f64, f64), time: f64) -> Self {
        Self {
            pixel,
            jitter,
            lens,
            time: time.clamp(0.0, 1.0),
        }
    }

    /// Samples all camera parameters from a stream and RNG.
    ///
    /// Consumes 2 stream pairs (4 values via `stream.next_2d()` twice: jitter xy and lens xy) + 1 from rng (time).
    pub fn new_sampled<S: SampleStream, R: SamplerRng>(
        pixel: (u32, u32),
        stream: &mut S,
        rng: &mut R,
    ) -> Self {
        let (jx, jy) = stream.next_2d();
        let (lx, ly) = stream.next_2d();
        Self {
            pixel,
            jitter: (jx, jy),
            lens: (lx, ly),
            time: rng.next().clamp(0.0, 1.0),
        }
    }
}

pub struct CameraRay {
    /// The ray generated by the camera for this sample, in world space.
    pub ray: Ray,
    /// The weight of the ray, which may include factors like lens sampling and motion blur.
    pub weight: Color3,
}

pub trait Camera: Send + Sync {
    /// Generates a ray for the given camera sample. The ray is in world space.
    fn generate_ray(&self, sample: &CameraSampler) -> Option<CameraRay>;

    /// Generates ray differentials for the given camera sample, if supported, for texture filtering and anti-aliasing.
    fn generate_ray_differential(&self, sample: &CameraSampler) -> Option<CameraRay> {
        let _ = sample;
        // No differentials by default, but can be overridden by cameras that support them (e.g. perspective camera).
        None
    }

    /// Returns the resolution of the camera's image plane (width, height).
    fn image_resolution(&self) -> (u32, u32);
}
